#!/usr/bin/env node

const fs = require('fs').promises;

let port = process.argv[2] || 8000;

fs.writeFile('./errors.txt');

console.log('building...');

require('child_process').execSync('npx sucrase -q ./src -d ./src-dist --transforms typescript,imports', {stdio: 'inherit'});
require('child_process').execSync('npx sucrase -q ./server -d ./server-dist --transforms jsx,typescript,imports', {stdio: 'inherit'});
require('child_process').execSync('npm test', {stdio: 'inherit'});

const Server = require('./server-dist/index');
const server = new Server();

server.createServer(port);

const YeetBot = require('./src-dist/index');
const client = new YeetBot();

client.loadCommands();

client.connect(client.token);
