#!/usr/bin/env node

console.log('building...');

if (!process.env.TOKEN) {
    console.log('be sure you have your token in here otherwise the bot won\'t start.');
    console.log('if you have your token in here and you see this. use "npm start" to start the bot.');
}


switch (process.argv[2]) {
    case '--production':
        require('child_process').execSync('npm run build', {stdio: 'inherit'});
    break;
    case '--development':
        require('child_process').execSync('npm run devbuild', {stdio: 'inherit'});
    break;
    default:
        require('child_process').execSync('npm run build', {stdio: 'inherit'});
    break;
}

console.log('starting...');

const ErioBot = require('./src-dist/index.js');

const bot = new ErioBot();

bot.loadCommands();

bot.connect(bot.client.token);

require('module')._load('./www-dist/server/app.js');