#!/usr/bin/env node

const fs = require('fs');

console.log('building...');
require('child_process').execSync('npm test', {stdio: 'inherit'});

const YeetBot = require('./dist/index.js');
const client = new YeetBot();

client.loadCommands();

client.connect(client.token);
