#!/usr/bin/env node
const { profileEnd } = require('console');
const PG = require('pg');
const { queries } = require('./config/queries.js');

// Use sucrase to compile the typescript
require('child_process').execSync('./node_modules/sucrase/bin/sucrase -q ./src -d ./src-dist --transforms jsx,typescript,imports', {stdio: 'inherit'});
require('child_process').execSync('./node_modules/sucrase/bin/sucrase -q ./www -d ./www-dist --transforms jsx,typescript,imports', {stdio: 'inherit'});

// Make and edit anything with databases
(async () => {
    if (!process.env.DATABASE_URL || process.env.PGUSER) return console.log('No database found.');
    const pool = new PG.Pool({
        connectionString: `${process.env.DATABASE_URL || `postgresql://${process.env.PGUSER}:${process.env.PGPASSWORD}@${process.env.PGHOST}:${process.env.PGPORT}/${process.env.PGDATABASE}`}`
    });
    for (const query of queries) {
        await pool.query(query);
    }
})();
